apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: db-vm
  labels:
    app: db-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: db-vm
        app: db-vm
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
        resources:
          requests:
            memory: 1024Mi
      volumes:
        - containerDisk:
            image: quay.io/containerdisks/fedora:latest
          name: containerdisk