apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
  namespace: my-test-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: image-registry.openshift-image-registry.svc:5000/my-test-project/my-web-app:latest
        ports:
        - containerPort: 8080