apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-hybrid-demo
  namespace: argocd-demo  
spec:
  project: default
  source:
    repoURL: 'https://github.com/justine-tkl/gitops-config.git'
    targetRevision: HEAD
    path: . 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
